name: fecipe
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get: ^4.6.5
  google_fonts: ^5.0.0
  auto_size_text: ^3.0.0
  floating_bottom_navigation_bar: ^1.5.2
  tbib_splash_screen: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.6.3
  equatable: ^2.0.5
  connectivity_plus: ^4.0.1
  cloud_firestore: ^4.8.2
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/images/
    - asset/json/


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "asset/images/launcher_icon.png"
  adaptive_icon_foreground: "asset/launcher_icon/foreground.png"
  adaptive_icon_background: "asset/launcher_icon/background.png"