// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0cV6BoYJaxwIEMvkWF0ymv0jdTB0ONc',
    appId: '1:1011545491006:web:c6f6e90ec45127561a336f',
    messagingSenderId: '1011545491006',
    projectId: 'fecipe-internal',
    authDomain: 'fecipe-internal.firebaseapp.com',
    storageBucket: 'fecipe-internal.appspot.com',
    measurementId: 'G-MVNFWZX3XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1TH1QqfnikrOLCoo3LcMJnipzJLmy_M',
    appId: '1:1011545491006:android:325096ed9e1847ca1a336f',
    messagingSenderId: '1011545491006',
    projectId: 'fecipe-internal',
    storageBucket: 'fecipe-internal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkSKqe_pLsina_fsfNI6D4BmX-6JXY-VM',
    appId: '1:1011545491006:ios:08dcd9d9119500061a336f',
    messagingSenderId: '1011545491006',
    projectId: 'fecipe-internal',
    storageBucket: 'fecipe-internal.appspot.com',
    iosClientId: '1011545491006-r2dsoa18h7o51usparc0j44be2sq5jpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkSKqe_pLsina_fsfNI6D4BmX-6JXY-VM',
    appId: '1:1011545491006:ios:9c87fec6e96bfeb41a336f',
    messagingSenderId: '1011545491006',
    projectId: 'fecipe-internal',
    storageBucket: 'fecipe-internal.appspot.com',
    iosClientId: '1011545491006-loggm4g0q9e138gaj6buf9iu0q6bklcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fecipe.RunnerTests',
  );
}
